# Generated by Django 5.1.6 on 2025-02-18 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(verbose_name='название компании заказчика')),
                ('customer_address', models.CharField(verbose_name='полный адрес компании заказчика')),
                ('customer_city', models.CharField(verbose_name='город компании заказчика')),
            ],
            options={
                'verbose_name': 'заказчик',
                'verbose_name_plural': 'заказчик',
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='DeviceInField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(verbose_name='серийный номер')),
                ('owner_status', models.CharField(verbose_name='статус заказа')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='crm_app.customer', verbose_name='идентификатор пользователя')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='crm_app.device', verbose_name='идентификатор оборудования')),
            ],
            options={
                'verbose_name': 'оборудование в полях',
                'verbose_name_plural': 'оборудование в полях',
                'db_table': 'device_in_field',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_description', models.CharField(verbose_name='описание заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='последнее изменение')),
                ('order_status', models.CharField(verbose_name='статус заявки')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='crm_app.customer', verbose_name='заказчик')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='crm_app.deviceinfield', verbose_name='оборудование')),
            ],
            options={
                'verbose_name': 'заявки',
                'verbose_name_plural': 'заявки',
                'db_table': 'order',
            },
        ),
    ]
